export const CREATE_DASHBOARD = 'CREATE_DASHBOARD';
export const TOGGLENEWDASHBOARDMODAL = 'TOGGLENEWDASHBOARDMODAL';
export const LOADSAVEDDASHBOARDS = 'LOADSAVEDDASHBOARDS';
export const DELETEDASHBOARD = 'DELETEDASHBOARD';
export const DISMISSALERT = 'DISMISSALERT';
